<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>BluecusliyouPackage</PackageId>
    <Version>1.0.0</Version>
    <Authors>bluecusliyou</Authors>
    <Description>功能描述</Description>
    <PackageTags>工具类,扩展</PackageTags>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
</Project>
